groupe:
    pattern:  /
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:index" }

groupe_show:
    pattern:  /{id}/show
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:show" }

groupe_new:
    pattern:  /new
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:new" }

groupe_create:
    pattern:  /create
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:create" }
    requirements: { _method: post }

groupe_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:editName" }

groupe_update:
    pattern:  /{id}/update
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:updateName" }
    requirements: { _method: post|put }

groupe_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:delete" }
    requirements: { _method: post|delete }

groupe_ask_delete:
    pattern: /{id}/ask_delete
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:askDelete" }

groupe_delete_user:
    pattern: /{groupe_id}/{user_id}/delete_user
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:deleteUser" }

groupe_delete_admin:
    pattern: /{groupe_id}/{admin_id}/delete_admin
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:deleteAdmin" }

groupe_show_members:
    pattern: /{id}/members
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:showMembers" }

groupe_add_users:
    pattern: /{id}/add_users
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:addUser" }

groupe_persist_users:
    pattern: /{id}/persist_users
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:persistUser" }
    requirements: { _method: post }

groupe_add_admins:
    pattern: /{groupe_id}/{admin_id}/add_admins
    defaults: { _controller: "ProjetL3GroupeBundle:Groupe:addAdmin" }