<?php

namespace ProjetL3\LienBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienRepository extends EntityRepository
{
    public function myFindAll()
    {
        // fonction à utiliser pour afficher tous les liens sur la page d'accueil
        return $this->createQueryBuilder('l')
            ->getQuery()
            ->getResult();
    }

    public function findLastPosts($duree){
        $date = new \DateTime();
        $date->add(new \DateInterval($duree));
        return $this->createQueryBuilder('u')
            ->where('u.date < ?1')
            ->setParameter(1,$date)
            ->getQuery()
            ->getResult();
    }

    public function findAllTrie($filtres) {
        $fieldsNames = $this->_em->getClassMetadata('ProjetL3LienBundle:Lien')->getFieldNames();
        $orderBy = array();
        foreach($fieldsNames as $fieldName) {
            if (isset($filtres[$fieldName.'_opt'])) {
                if($filtres[$fieldName.'_opt']!='None') {
                    $orderBy[$fieldName]=$filtres[$fieldName.'_opt'];
                }
            }
        }
        return $this->findBy(array(),$orderBy);
    }

    public function findByThemes($theme) {
        return $this->createQueryBuilder('l')
            ->select('l')
            ->innerJoin('l.listes','t')
            ->where('t.nom = ?1')
            ->setParameter(1,$theme)
            ->getQuery()
            ->getResult();
    }

}
