parameters:
#    projet_l3_liste.example.class: ProjetL3\ListeBundle\Example

services:
#    projet_l3_liste.example:
#        class: %projet_l3_liste.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    projet_l3_liste.admin.liste:
        class: ProjetL3\ListeBundle\Admin\ListeAdmin
        arguments: [~, ProjetL3\ListeBundle\Entity\Liste, ProjetL3ListeBundle:ListeAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Liste}
