<?php

namespace ProjetL3\LienBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteLienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteLienRepository extends EntityRepository
{
}
