ProjetL3\TagBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: ProjetL3\TagBundle\Entity\TagRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nom:
            type: string
            length: 255
            unique: true
    manyToMany:
        liens:
            cascade: [ "persist", "merge", "detach" ]
            targetEntity: ProjetL3\LienBundle\Entity\Lien
            inversedBy: tags
            joinTable:
                name: lien_tags
                joinColumns:
                    tag_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    lien_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
