ProjetL3\UserBundle\Entity\User:
    properties:
        freqActu:
          - Choice: { choices: [semaine, jour, aucune], message: Choisir une fréquence d'envoi des news. }
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity : [nom, prenom]